rate:
  starter:
    mode: date-range
    currencies[0]: EUR
    currencies[1]: USD

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: currencyRates