spring:
  application:
    name: ContractService

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: idp

  liquibase:
    enabled: true
    default-schema: idp
    liquibase-schema: liquibase
